### ISSUE TITLE
Genetic Observation

### ISSUE THREAD

**Issue by bwalsh** [ACED-IDP/data_model#18]
There are a number of observations in the synthetic data of this form:

```
  "code": {
        "coding": [ {
          "system": "http://loinc.org/",
          "code": "69548-6",
          "display": "The PSRC1 gene exhibits a variation of 'Uncertain' clinical significance. The variation at index rs599839_FS1 is associated with an increased risk of: Cardiovascular Issues, Dsyslipidemia, Heart Disease, High LDL and Aortic Aneurysm."
        } ],

```

They all refer to a genomic variant assessment https://loinc.org/69548-6/

The observations are missing a category.  
•	Expected in that the FHIR category https://build.fhir.org/valueset-observation-category.html#expansion doesn’t have one for genetics. 
•	My thought was to insert a category of   https://loinc.org/55233-1/   -  Genetic analysis master panel

Additionally, I'd like to extract more meaning from the observation.  After parsing a representative sentence, this is what I'm considering: 

"The PSRC1 gene exhibits a variation of 'Uncertain' clinical significance. The variation at index rs599839_FS1 is associated with an increased risk of: Cardiovascular Issues, Dsyslipidemia, Heart Disease, High LDL and Aortic Aneurysm."

We have roughly:

•	gene: PSRC1
•	significance: Uncertain
•	variant: rs599839
•	phenotype: increased risk
•	conditions: [Cardiovascular Issues, Dsyslipidemia, Heart Disease, High LDL and Aortic Aneurysm]

Mapping to a more formal definition of variant: http://build.fhir.org/ig/HL7/genomics-reporting/StructureDefinition-variant.html#terminology-bindings 

•	Observation.component:gene-studied.value : PSRC1
•	Observation.component:genomic-ref-seq.value: rs599839

and a more formal definition of implication: http://build.fhir.org/ig/HL7/genomics-reporting/StructureDefinition-diagnostic-implication.html

•	[Observation.component:conclusion-string](http://build.fhir.org/ig/HL7/genomics-reporting/StructureDefinition-diagnostic-implication-definitions.html#Observation.component:conclusion-string): “The PSRC1 gene exhibits a variation … “
•	https://loinc.org/53037-8/  or https://loinc.org/LL5356-2/ : uncertain
•	[Predicted phenotype](http://build.fhir.org/ig/HL7/genomics-reporting/StructureDefinition-diagnostic-implication-definitions.html#Observation.component:predicted-phenotype): Cardiovascular Issues, Dsyslipidemia, Heart Disease, High LDL and Aortic Aneurysm."
•	http://hl7.org/fhir/R4/valueset-observation-interpretation.html: “increased risk”

**Comment by bwalsh** [comment]
@jordan2lee @lbeckman314

**Comment by bwalsh** [comment]
@matthewpeterkort

**Comment by bwalsh** [comment]
### Histograms

#### Gene

Note `CDKN2B ,` - embedded comma. might have a parsing problem there.

<img width="774" alt="image" src="https://user-images.githubusercontent.com/47808/203145181-e001b81e-88e9-45d9-8e33-06adb89706a5.png">


#### Variant

Note:  seems like a reasonable figure.  Parsing seems OK, all SNP ids.

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/47808/203145751-bf713156-cd5f-423b-8c81-6fdd51cd7df9.png">

#### Significance

Note:  I wonder what `Association` means.

<img width="585" alt="image" src="https://user-images.githubusercontent.com/47808/203145895-b8372837-aefc-486d-a1de-aebf4bc225e8.png">

#### Risk

Note: Pretty boring.  All `increased risk`.


<img width="703" alt="image" src="https://user-images.githubusercontent.com/47808/203146074-d1a4bb6a-f390-411e-b4f9-1b1175bd4596.png">

**Comment by bwalsh** [comment]
[observations.csv](https://github.com/ACED-IDP/data_model/files/10060175/observations.csv)

**Comment by bwalsh** [comment]
Two occurrences of comma in gene string.   AFAIK, this appears to be a decoration on the name of the gene, not a separate gene. see https://www.genecards.org/cgi-bin/carddisp.pl?gene=LOC100287329 https://www.genecards.org/cgi-bin/carddisp.pl?gene=CDKN2B-AS1

"The `CDKN2B, CDKN2B-AS1` gene exhibits a variation of 'Uncertain' clinical significance. The variation at index rs3217992_FS1 is associated with an increased risk of: Ischemic Stroke."

"The `LOC100287329, LTA` gene exhibits a variation of 'Risk Factor' clinical significance. The variation at index rs1041981_FS2 is associated with an increased risk of: Ischemic Stroke."

**Comment by jordan2lee** [comment]
@bwalsh's comment of "Significance Note: I wonder what Association means." - it looks like this may be how reporting was done (different sources use slightly different terms to mean the same thing), but to be sure if this is the case, we could look at the sources where Association comes from (do they all come from the same soure?).

there is only one gene that uses the term "Association" 
<img width="717" alt="image" src="https://user-images.githubusercontent.com/40308471/203152987-bbde2699-3872-4418-a58b-7ce3d2db2fcf.png">

The alternative explanation is that "Association" is used when the study doesn't report detailed significance as seen from  https://www.pharmgkb.org/clinicalAnnotation/1444700522

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/40308471/203153214-c196df4f-1bce-49f5-a09c-0ffb1793e0d6.png">

**Comment by jordan2lee** [comment]
I would suggest that the category “significance” be changed to “clinical_significance” because it clarifies what is meant. Avoids statisticians misunderstanding that these gene, significance, variant, phenotype, or conditions is either uncertain statistically or clinically.

**Comment by bwalsh** [comment]
Thanks,  this was the original sentence: `"The ABCG2 gene exhibits a variation of 'Association' clinical significance. The variation at index rs2231137_FS1 is associated with an increased risk of: Cardiovascular Issues and Ischemic Stroke."`

**Comment by jordan2lee** [comment]
Will also want to connect these SNP (rs IDs) to allele as per 
![image](https://user-images.githubusercontent.com/40308471/203159087-714030a2-2709-48ec-b40d-2d220e779fb3.png)
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4288081/

**Comment by bwalsh** [comment]
>  Avoids statisticians misunderstanding that these gene, significance, variant, phenotype, or conditions is either uncertain statistically or clinically.

Exactly.  The target for the final names is the population of concept codes we apply:

```
and a more formal definition of implication: http://build.fhir.org/ig/HL7/genomics-reporting/StructureDefinition-diagnostic-implication.html

• [Observation.component:conclusion-string](http://build.fhir.org/ig/HL7/genomics-reporting/StructureDefinition-diagnostic-implication-definitions.html#Observation.component:conclusion-string): “The PSRC1 gene exhibits a variation … “
• https://loinc.org/53037-8/ or https://loinc.org/LL5356-2/ : uncertain
• [Predicted phenotype](http://build.fhir.org/ig/HL7/genomics-reporting/StructureDefinition-diagnostic-implication-definitions.html#Observation.component:predicted-phenotype): Cardiovascular Issues, Dsyslipidemia, Heart Disease, High LDL and Aortic Aneurysm."
• http://hl7.org/fhir/R4/valueset-observation-interpretation.html: “increased risk”
```

**Comment by jordan2lee** [comment]
`VariationId` for the snp id is a codable concept and is specified as for dbSNP ids already. `rs599839` = geneid under geneticObservation

![image](https://user-images.githubusercontent.com/40308471/203160291-e5739173-b3dd-4f0b-85ff-12dc33d33915.png)

The full paper this image is from likely will also be useful to us https://academic.oup.com/jamia/article/22/6/1173/2357593

so perhaps for geneticobservation:
 geneid: PSRC1
• VariationId: rs599839
• Interpretation: Uncertain
• Interpretation: increased risk
• AssessedCondition: [Cardiovascular Issues, Dsyslipidemia, Heart Disease, High LDL and Aortic Aneurysm]

**Comment by jordan2lee** [comment]
also https://fhir.arkhn.com/osiris/StructureDefinition-snp.html

**Comment by bwalsh** [comment]
#### snp capture?

All the variants have a `_FS[x]` suffix.

<img width="595" alt="image" src="https://user-images.githubusercontent.com/47808/203171731-c8f633c2-f7f2-42a7-b736-b204e531d199.png">

`Unsure` what FS stands for: Follistatin? FeatureSelection ? Capture? Frame Shift ?
Settled on `capture` for now.   

https://www.researchgate.net/publication/327396309_Genomic_selection_prediction_models_comparing_sequence_capture_and_SNP_array_genotyping_methods/figures?lo=1

sample of values

```


rs5361_FS1 
rs1048990_FS2
rs1048990_FS1
rs599839_FS2
rs662_FS2
rs1041981_FS2
rs966221_FS1
rs10757278_FS2
rs2383206_FS2
rs4420638_FS2
rs7439293_FS2
rs10757274_FS1

```

**Comment by jordan2lee** [comment]
I wonder if the FS1/2 is an artifact of the Synthea dataset, while in real datasets we won't encounter it

![image](https://user-images.githubusercontent.com/40308471/203182832-82c92035-5cbe-4fcf-88fa-abd106fa0048.png)
Image from the Coherent paper https://www.mdpi.com/2079-9292/11/8/1199/htm

**Comment by bwalsh** [comment]
@jordan2lee  thanks. ^^ dropped the capture for now.

**Comment by bwalsh** [comment]
@jordan2lee  Let me know what you think.

# BEFORE
```
category:
- coding:
  - system: http://terminology.hl7.org/CodeSystem/observation-category
code:
  coding:
  - code: 69548-6
    display: 'The CCL2 gene exhibits a variation of ''Pathogenic'' clinical significance.
      The variation at index rs1024611_FS1 is associated with an increased risk of:
      Ischemic Stroke and Pulmonary Hypertension.'
    system: http://loinc.org
  text: 'The CCL2 gene exhibits a variation of ''Pathogenic'' clinical significance.
    The variation at index rs1024611_FS1 is associated with an increased risk of:
    Ischemic Stroke and Pulmonary Hypertension.'
effectiveDateTime: '1988-05-03T22:18:07-04:00'
encounter:
  reference: Encounter/a596d252-822b-4b39-b77e-517cac754dd6
id: 2b664845-e534-4006-9b51-253bc44b0b11
issued: '1988-05-03T22:18:07.591-04:00'
meta:
  lastUpdated: '2022-11-19T14:24:47.591+00:00'
  source: '#0AWBFvLDRTkd4HUI'
  versionId: '1'
resourceType: Observation
status: final
subject:
  reference: Patient/1265b2d4-8719-4622-b17f-7d0a722b5750
```
# AFTER
```
category:
- coding:
  - code: 55233-1
    display: Genetic analysis master panel
    system: https://loinc.org
  - code: laboratory
    display: laboratory
    system: http://terminology.hl7.org/CodeSystem/observation-category
code:
  coding:
  - code: diagnostic-implication
    system: http://hl7.org/fhir/uv/genomics-reporting/CodeSystem/tbd-codes-cs
component:
- code:
    coding:
    - code: 48018-6
      display: Gene studied ID
      system: http://loinc.org
  valueCodeableConcept:
    coding:
    - code: CCL2
      display: CCL2
      system: http://www.genenames.org/geneId
- code:
    coding:
    - code: 48013-7
      display: Genomic reference sequence ID
      system: http://loinc.org
  valueCodeableConcept:
    coding:
    - code: rs1024611
      display: rs1024611
      system: https://www.ncbi.nlm.nih.gov/snp/
- code:
    coding:
    - code: conclusion-string
      display: conclusion-string
      system: http://hl7.org/fhir/uv/genomics-reporting/CodeSystem/tbd-codes-cs
  valueString: 'The CCL2 gene exhibits a variation of ''Pathogenic'' clinical significance.
    The variation at index rs1024611_FS1 is associated with an increased risk of:
    Ischemic Stroke and Pulmonary Hypertension.'
- code:
    coding:
    - code: evidence-level
      display: evidence-level
      system: http://hl7.org/fhir/uv/genomics-reporting/CodeSystem/tbd-codes-cs
  valueCodeableConcept:
    coding:
    - code: 'TODO lookup code for: Pathogenic'
      display: Pathogenic
      system: http://loinc.org/LL5356-2/
- code:
    coding:
    - code: predicted-phenotype
      display: predicted-phenotype
      system: http://hl7.org/fhir/uv/genomics-reporting/CodeSystem/tbd-codes-cs
  valueCodeableConcept:
    coding:
    - code: TODO - lookup snomed code for Ischemic Stroke
      display: Ischemic Stroke
      system: http://snomed.info/sct
    - code: TODO - lookup snomed code for Pulmonary Hypertension
      display: Pulmonary Hypertension
      system: http://snomed.info/sct
- code:
    coding:
    - code: observation-interpretation
      display: observation-interpretation
      system: http://hl7.org/fhir/uv/genomics-reporting/CodeSystem/tbd-codes-cs
  valueCodeableConcept:
    coding:
    - code: moderate
      display: The specified outcome has a reasonable likelihood of occurrence.
      system: http://terminology.hl7.org/CodeSystem/risk-probability
effectiveDateTime: '1988-05-03T22:18:07-04:00'
encounter:
  reference: Encounter/a596d252-822b-4b39-b77e-517cac754dd6
id: 2b664845-e534-4006-9b51-253bc44b0b11
issued: '1988-05-03T22:18:07.591-04:00'
meta:
  lastUpdated: '2022-11-19T14:24:47.591+00:00'
  source: '#0AWBFvLDRTkd4HUI'
  versionId: '1'
resourceType: Observation
status: final
subject:
  reference: Patient/1265b2d4-8719-4622-b17f-7d0a722b5750
```
