### ISSUE TITLE
As a BMEG/GRIP engineer, I need an updated schema to use to control ingestion of ACED data

### ISSUE THREAD

**Issue by bwalsh** [ACED-IDP/data_model#27]

**Comment by kellrott** [comment]
Example of link generation

```
  samples:
    targets: 
      - type: 
          $ref: sample.yaml
        backref: case
    $ref: _definitions.yaml#/to_many
```
